### ISSUE TITLE
Source generation

### ISSUE THREAD

**Issue by Eunoia** [mkearney/presidential_election_county_results_2016#6]
Hey Michael,

I'm a huge fan of this project, and I've been using the data for some interesting analysis. 

As my project concludes, I'd love to know the source of this data, and the process by which it's been generated. 

Thank you so much for aggregating the election results, and sharing them on Github.

-Evan

**Comment by mkearney** [comment]
Evan,

I'm glad you're enjoying the data :). The files were made using publicly available AP data. I scraped and wrangled the data using the R environment.
